# Generated by Django 6.0.1 on 2026-01-28 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode_app', '0003_barcode_scans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcode',
            name='scans',
            field=models.IntegerField(default=0),
        ),
    ]
