# Generated by Django 5.2.7 on 2026-04-08 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode_app', '0005_alter_barcode_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='barcode',
            name='price',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
