# Generated by Django 5.2.7 on 2026-04-08 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode_app', '0006_barcode_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barcode',
            name='description',
        ),
        migrations.RemoveField(
            model_name='barcode',
            name='price',
        ),
        migrations.RemoveField(
            model_name='barcode',
            name='product_image',
        ),
        migrations.RemoveField(
            model_name='barcode',
            name='url',
        ),
        migrations.AlterField(
            model_name='barcode',
            name='type',
            field=models.CharField(choices=[('link', 'لينك'), ('menu', 'منيو')], default='menu', max_length=10),
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('description', models.TextField(blank=True, null=True)),
                ('barcode', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='link', to='barcode_app.barcode')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('barcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='barcode_app.barcode')),
            ],
        ),
    ]
